apiVersion: apps/v1
kind: Deployment
metadata:
  name: humix-album-api
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: humix-album-api
  template:
    metadata:
      labels:
        app: humix-album-api
    spec:
      containers:
      - name: humix-album-api
        image: humix-album-api
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_jTOzam35HwXA@ep-shy-pond-a88cp7xz-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"