apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: album

images:
- name: humix-album-api
  newName: blgianinis/humix-album-api
  newTag: daa9a1695351feedae2ef4ecd802d5a6c8b5f379
